# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E1C1C)
$foreground = rgb(E7DFD3)
$color0 = rgb(454342)
$color1 = rgb(1A1412)
$color2 = rgb(352923)
$color3 = rgb(3B2E27)
$color4 = rgb(5A4D3A)
$color5 = rgb(655746)
$color6 = rgb(8B7B61)
$color7 = rgb(D4C9B8)
$color8 = rgb(948D80)
$color9 = rgb(231B18)
$color10 = rgb(47372F)
$color11 = rgb(4E3E34)
$color12 = rgb(78664D)
$color13 = rgb(87745D)
$color14 = rgb(B9A481)
$color15 = rgb(D4C9B8)
