# /* ---- Rick's Startup Apps ---- */
# Sintaxe: [workspace X silent] → abre no workspace X sem mudar o foco pra lá

exec-once = [workspace 1 silent] cursor
exec-once = [workspace 2 silent] flatpak run com.brave.Browser
exec-once = [workspace 3 silent] flatpak run md.obsidian.Obsidian
exec-once = [workspace 5 silent] flatpak run com.rafaelmardojai.Blanket
exec-once = [workspace special silent] flatpak run com.spotify.Client