# /* ---- Rick's Startup Apps ---- */
# Sintaxe: [workspace X silent] → abre no workspace X sem mudar o foco pra lá

# Workflow 1: Claude Desktop, Terminal, Cursor
exec-once = [workspace 1 silent] cursor
exec-once = [workspace 1 silent] claude-desktop-unofficial
exec-once = [workspace 1 silent] kitty

# Workflow 2: Brave
exec-once = [workspace 2 silent] flatpak run com.brave.Browser

# Workflow 3: Obsidian
exec-once = [workspace 3 silent] flatpak run md.obsidian.Obsidian

# Workflow 4: Docker (o daemon já sobe sozinho via systemd, isso só abre o terminal) + Terminal
exec-once = [workspace 4 silent] kitty

# Workflow 5: Blanket
exec-once = [workspace 5 silent] flatpak run com.rafaelmardojai.Blanket

# Workflow 6: CoreCtrl (precisa da regra polkit em /etc/polkit-1/rules.d/90-corectrl.rules)
exec-once = [workspace 6 silent] corectrl

exec-once = [workspace special silent] flatpak run com.spotify.Client