# /* ---- Rick's Startup Apps ---- */
# Sintaxe: [workspace X silent] → abre no workspace X sem mudar o foco pra lá

# Workflow 1: Terminal e Zed
exec-once = [workspace 1 silent] kitty
exec-once = [workspace 1 silent] zed --new

# Workflow 2: Terminal e Zed
exec-once = [workspace 2 silent] kitty
exec-once = [workspace 2 silent] zed --new

# Workflow 3: Brave Browser e Brave Origin
exec-once = [workspace 3 silent] brave-browser-stable
exec-once = [workspace 3 silent] brave-origin-stable

# Workflow 4: Obsidian
exec-once = [workspace 4 silent] flatpak run md.obsidian.Obsidian

# Workflow 5: Blanket
exec-once = [workspace 5 silent] flatpak run com.rafaelmardojai.Blanket

# Workflow 6: CoreCtrl (precisa da regra polkit em /etc/polkit-1/rules.d/90-corectrl.rules)
exec-once = [workspace 6 silent] corectrl

exec-once = [workspace special silent] flatpak run com.spotify.Client
