# /* ---- Rick's Custom Keybinds ---- */

$mainMod = SUPER
$scriptsDir = $HOME/.config/hypr/scripts

# ══════════════════════════════════════════
# UNBINDS — remover só o necessário
# ══════════════════════════════════════════

# Tira o keyboard layout switcher
unbind = ALT_L, SHIFT_L
unbind = SHIFT_L, ALT_L


# Tira SUPER+I (era addmaster) pra liberar pra foco cima
unbind = SUPER, I

# Tira SUPER+SPACE (era togglefloating) pra liberar pro Rofi
unbind = SUPER, SPACE

# Tira SUPER+CTRL+SPACE pra liberar pra bind de burlar os anúncios do Spotify
unbind = SUPER CTRL, S

# ══════════════════════════════════════════
# SUPER + SPACE → Rofi
# ══════════════════════════════════════════

bindd = $mainMod, SPACE, app launcher, exec, pkill rofi || true && rofi -show drun -modi drun,filebrowser,run,window

# ══════════════════════════════════════════
# SUPER + IJKL → Foco de janelas
# ══════════════════════════════════════════

bindd = $mainMod, I, focus up, movefocus, u
bindd = $mainMod, J, focus left, movefocus, l
bindd = $mainMod, K, focus down, movefocus, d
bindd = $mainMod, L, focus right, movefocus, r

# ══════════════════════════════════════════
# CTRL + ALT + SETAS → Navegar workspaces
# ══════════════════════════════════════════

bindd = CTRL ALT, right, next workspace, workspace, e+1
bindd = CTRL ALT, left, previous workspace, workspace, e-1

# ══════════════════════════════════════════
# CTRL + SHIFT + ALT + SETAS → Mover janela pro workspace ao lado
# ══════════════════════════════════════════

bindd = CTRL SHIFT ALT, right, move window to next workspace, movetoworkspace, e+1
bindd = CTRL SHIFT ALT, left, move window to previous workspace, movetoworkspace, e-1

# ══════════════════════════════════════════
# CTRL + ALT + S → Special Workspace (Spotify)
# ══════════════════════════════════════════

bindd = CTRL ALT, S, toggle special workspace, togglespecialworkspace,

# ══════════════════════════════════════════
# SHIFT + ALT + 1-5 → Mídia e Volume
# ══════════════════════════════════════════

bindd = SHIFT ALT, code:10, previous track, exec, $scriptsDir/MediaCtrl.sh --prv
bindd = SHIFT ALT, code:11, play/pause, exec, $scriptsDir/MediaCtrl.sh --pause
bindd = SHIFT ALT, code:12, next track, exec, $scriptsDir/MediaCtrl.sh --nxt
bindd = SHIFT ALT, code:13, volume down, exec, $scriptsDir/Volume.sh --dec
bindd = SHIFT ALT, code:14, volume up, exec, $scriptsDir/Volume.sh --inc

# ══════════════════════════════════════════
# Keybind pra burlar anúncios no Spotify (reinicia o Spotify automaticamente e coloca pra tocar de novo)
# ══════════════════════════════════════════
bind = SUPER CTRL, S, exec, bash -c 'pkill spotify; sleep 0.5 && flatpak run com.spotify.Client & sleep 4 && playerctl --player=spotify play'